### ISSUE TITLE
Selector with nth-child does not work

### ISSUE THREAD

**Issue by PikachuEXE** [Mange/roadie#49]
Rails `3.2.12`, Roadie `2.3.4`, nokogiri `1.5.6`
I want alternative row background color effect
So I tried:

``` css
  .job-row:nth-child(2n) {
    background-color: $grey-lighter;
  }

  .job-row:nth-child(2n+1) {
    background-color: $grey-lighter;
  }
```

The code itself has no error.
I tested it by pasting the selector to inspector in Chrome
I am not sure if its the problem of `roadie` or one of dependencies

I am using this for the effect right now

``` haml
.job-row(class: cycle('row-odd', 'row-even'))
```
