### ISSUE TITLE
CSS3 styling is ignored

### ISSUE THREAD

**Issue by kenearley** [Mange/roadie#7]
I'm using compass/sass on a rails project and the css3 stylings (ie: border-radius, box-shadow) are not being added to the inline styles. Am I missing something?

**Example css output:**

``` css
.goal_stats table tr td div {
  background: #41a0cf;
  border: 1px solid #1f88bd;
  -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
  -o-border-radius: 2px;
  -ms-border-radius: 2px;
  -khtml-border-radius: 2px;
  border-radius: 2px;
  color: white;
  font-size: 11px;
  margin: 0 7px;
  padding: 15px;
  text-transform: uppercase;
  -moz-box-shadow: #62b0d7 1px 1px 1px 1px inset, #aaaaaa 1px 1px 3px 0;
  -webkit-box-shadow: #62b0d7 1px 1px 1px 1px inset, #aaaaaa 1px 1px 3px 0;
  -o-box-shadow: #62b0d7 1px 1px 1px 1px inset, #aaaaaa 1px 1px 3px 0;
  box-shadow: #62b0d7 1px 1px 1px 1px inset, #aaaaaa 1px 1px 3px 0;
}
```

**Corresponding output in Gmail (Chrome):**

``` html
<div style="font:inherit;vertical-align:baseline;border:1px solid #1f88bd;background:#41a0cf;color:white;font-size:11px;margin:0 7px;padding:15px;text-transform:uppercase">
              <strong style="margin:0;padding:0;border:0;vertical-align:baseline;font:inherit;display:block;font-size:44px;margin-bottom:15px">81 Days</strong>
              Average Goal Duration
            </div>
```

**Environment info:**
rails 3.0.10
ruby-1.9.2-p290
roadie 1.1.0
